import re
with open('app/app/page.tsx', 'r', encoding='utf8') as f: c = f.read()
c = c.replace('s? ATENaO: VocG esto', '?? ATENÇÃO: Você está')
c = c.replace('s Enriquecer Lote', '?? Enriquecer Lote')
c = c.replace('o% Disparo E-mails', '?? Disparo E-mails')
c = c.replace('Y\\' Gerar Wpp', '?? Gerar Wpp')
c = c.replace('Y" Gerar Insta', '?? Gerar Insta')
c = c.replace('Y"~ Gerar FB', '?? Gerar FB')
c = c.replace('Y-\\' s/ Insta', '??? s/ Insta')
c = c.replace('s? Limpar Tudo', '?? Limpar Tudo')
c = c.replace('s Enviar E-mail', '?? Enviar E-mail')
c = c.replace('Y"? Enriquecer', '?? Enriquecer')
c = c.replace('o% E-mail', '?? E-mail')
c = c.replace('Y-\\' Excluir', '??? Excluir')
c = c.replace('o. copiado', '? copiado')
c = c.replace('% Copiar', '?? Copiar')
c = c.replace('o Landing', '?? Landing')
c = c.replace('Y\\'', '??')
c = c.replace('Y"', '??')
c = c.replace('-Z', '??')
c = c.replace('', 'á')
with open('app/app/page.tsx', 'w', encoding='utf8') as f: f.write(c)
